Started on 03/21/16 22:37:30
    TestAnotherThing.testFail1 ... FAIL
test/test_with_err_fail_pass.lua:41: expected: 0, actual: 2
    TestAnotherThing.testFail2 ... FAIL
test/test_with_err_fail_pass.lua:45: expected: 0, actual: 3
    TestAnotherThing.testSuccess1 ... Ok
    TestAnotherThing.testSuccess2 ... Ok
    TestSomething.testFail1 ... FAIL
test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
    TestSomething.testFail2 ... FAIL
test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
    TestSomething.testSuccess1 ... Ok
    TestSomething.testSuccess2 ... Ok
    testFuncFail1 ... FAIL
test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
    testFuncSuccess1 ... Ok
=========================================================
Failed tests:
-------------
1) TestAnotherThing.testFail1
test/test_with_err_fail_pass.lua:41: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.lua:41: in function 'TestAnotherThing.testFail1'

2) TestAnotherThing.testFail2
test/test_with_err_fail_pass.lua:45: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:45: in function 'TestAnotherThing.testFail2'

3) TestSomething.testFail1
test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.lua:15: in function 'TestSomething.testFail1'

4) TestSomething.testFail2
test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:19: in function 'TestSomething.testFail2'

5) testFuncFail1
test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:62: in function 'testFuncFail1'

Ran 10 tests in 0.000 seconds, 5 successes, 5 failures, 5 non-selected
