1..10
# Started on 03/21/16 22:23:18
# Starting class: TestAnotherThing
not ok 1	TestAnotherThing.testFail1
    test/test_with_err_fail_pass.lua:41: expected: 0, actual: 2
    stack traceback:
    	test/test_with_err_fail_pass.lua:41: in function 'TestAnotherThing.testFail1'
not ok 2	TestAnotherThing.testFail2
    test/test_with_err_fail_pass.lua:45: expected: 0, actual: 3
    stack traceback:
    	test/test_with_err_fail_pass.lua:45: in function 'TestAnotherThing.testFail2'
ok     3	TestAnotherThing.testSuccess1
ok     4	TestAnotherThing.testSuccess2
# Starting class: TestSomething
not ok 5	TestSomething.testFail1
    test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
    stack traceback:
    	test/test_with_err_fail_pass.lua:15: in function 'TestSomething.testFail1'
not ok 6	TestSomething.testFail2
    test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
    stack traceback:
    	test/test_with_err_fail_pass.lua:19: in function 'TestSomething.testFail2'
ok     7	TestSomething.testSuccess1
ok     8	TestSomething.testSuccess2
not ok 9	testFuncFail1
    test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
    stack traceback:
    	test/test_with_err_fail_pass.lua:62: in function 'testFuncFail1'
ok     10	testFuncSuccess1
# Ran 10 tests in 0.000 seconds, 5 successes, 5 failures, 5 non-selected
